name: CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container Environment
        uses: devcontainers/ci@v0.3.1900000349
        with:
          imageName: ghcr.io/amacal/i13c
          cacheFrom: ghcr.io/amacal/i13c
          push: always
          runCmd: make clean build test
