name: CI/CD Workflow

on:
  workflow_dispatch:
  pull_request:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Container Environment
        uses: devcontainers/ci@v0.3.1900000349
        with:
            inheritEnv: true
            runCmd: make clean build test
