name: CI/CD Workflow

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image hash
        id: hash
        run: |
          cat .devcontainer/devcontainer.json .devcontainer/Dockerfile > .combined
          export HASH=$(sha256sum .combined | cut -c1-12)
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Container Environment
        uses: devcontainers/ci@v0.3.1900000349
        with:
          imageName: ghcr.io/amacal/i13c
          imageTag: ${{ steps.hash.outputs.hash }}
          push: always
          runCmd: make clean build test lint

      - name: Upload Built Binaries
        uses: actions/upload-artifact@v4
        with:
          name: i13c-binaries
          path: |
            bin/i13c-thrift
            bin/i13c-parquet
            LICENSE
            README.md

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: i13c-binaries

      - name: Make Release Package
        run: make release

      - name: Upload Release .tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: i13c-tarball
          path: release/*.tar.gz

      - name: Upload Release .deb
        uses: actions/upload-artifact@v4
        with:
          name: i13c-deb
          path: release/*.deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            i13c ${{ github.ref_name }}

            Changes:
            - Parquet parser: `i13c-parquet`

          files: |
            release/*.tar.gz
            release/*.deb
