name: CI/CD Workflow

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image hash
        id: hash
        run: |
          cat .devcontainer/devcontainer.json .devcontainer/Dockerfile > .combined
          export HASH=$(sha256sum .combined | cut -c1-12)
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Container Environment
        uses: devcontainers/ci@v0.3.1900000349
        with:
          imageName: ghcr.io/amacal/i13c
          imageTag: ${{ steps.hash.outputs.hash }}
          push: always
          runCmd: make clean build test lint

      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: i13c-binaries
          path: |
            bin/i13c-thrift
            LICENSE
            README.md

  release:
    runs-on: ubuntu-latest
    needs: cicd
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: i13c-binaries

      - name: Make release package
        run: make release
